### ISSUE TITLE
How do I export model to a file?

### ISSUE THREAD

**Issue by kirk0306** [ALRhub/deep_rl_for_swarms#7]
May I ask how to save the trained model to a local path? I tried to modify `def save(self, path=none)` in act_wrapper.py, but i didn't succeed.

**Comment by kirk0306** [comment]
I don't know if I did it right, I just add 
```
if rank == 0:
    logger.dump_tabular()
pi.save()
```
in trpo_mpi.py

**Comment by xinyu-site** [comment]
Have you solved this problem

> I don't know if I did it right, I just add
> 
> ```
> if rank == 0:
>     logger.dump_tabular()
> pi.save()
> ```
> 
> in trpo_mpi.py

I  try to save the trained model to a local path.Have you solved this problem？

**Comment by kirk0306** [comment]
> Have you solved this problem
> 
> > I don't know if I did it right, I just add
> > ```
> > if rank == 0:
> >     logger.dump_tabular()
> > pi.save()
> > ```
> > 
> > 
> > in trpo_mpi.py
> 
> I try to save the trained model to a local path.Have you solved this problem？

Yes, there will be some models in the TEMP folder if you add `pi.save()` after that, it works for me :)
